### ISSUE TITLE
datamanager exits with KeyError: 3

### ISSUE THREAD

**Issue by klutzzykitty** [sekilab/VehicleReIdentificationDataset#1]
Thanks for the dataset, it's a good intro data into getting started with Re-ID.
However, i've encountered an issue while following the instructions   xD
```
# You can change these hyperparameters as you wish
datamanager = torchreid.data.ImageDataManager(

    root='',
    sources='synthtetic_veri_reid',
    height = 256,
    width = 256,
    transforms =['random_flip', 'random_crop'])
```
    
The above block raises a `KeyError: 3`  from `class VeRiDataset`  `car_id = label_dict[int(image.split('.jpg')[0].split('_')[-1])]`

Is it that the dictionary isn't getting assigned the required key from that `split` operation ? 

Also, the `torchreid` instructions don't have the `root` empty as per the   [custom dataset example ](https://github.com/KaiyangZhou/deep-person-reid/blob/5d82902b3c994db31cfb35e6d35dfdade3a1711c/docs/user_guide.rst)  

`torchreid` module wasn't in the conda` mdx_reid.yml ` for which i've installed  torchreid==0.2.5 through pip

I suppose the error is from the split logic or is there anything else that might be causing it ? 
`path_to_dataset` is pointing to the directory that contains the three data folders of gallery, query and train. 

attaching the full trace-back below for reference: 
##############################################################################

Building train transforms ...
+ resize to 256x256
+ random flip
+ random crop (enlarge to 288x288 and crop 256x256)
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x256
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [7], in <cell line: 2>()
      1 # You can change these hyperparameters as you wish
----> 2 datamanager = torchreid.data.ImageDataManager(
      3     root='reid-data',
      4     sources='synthtetic_veri_reid',
      5     height = 256,
      6     width = 256,
      7     transforms =['random_flip', 'random_crop'])

File ~/anaconda3/envs/mdx_reid/lib/python3.9/site-packages/torchreid/data/datamanager.py:195, in ImageDataManager.__init__(self, root, sources, targets, height, width, transforms, k_tfm, norm_mean, norm_std, use_gpu, split_id, combineall, load_train_targets, batch_size_train, batch_size_test, workers, num_instances, num_cams, num_datasets, train_sampler, train_sampler_t, cuhk03_labeled, cuhk03_classic_split, market1501_500k)
    193 trainset = []
    194 for name in self.sources:
--> 195     trainset_ = init_image_dataset(
    196         name,
    197         transform=self.transform_tr,
    198         k_tfm=k_tfm,
    199         mode='train',
    200         combineall=combineall,
    201         root=root,
    202         split_id=split_id,
    203         cuhk03_labeled=cuhk03_labeled,
    204         cuhk03_classic_split=cuhk03_classic_split,
    205         market1501_500k=market1501_500k
    206     )
    207     trainset.append(trainset_)
    208 trainset = sum(trainset)

File ~/anaconda3/envs/mdx_reid/lib/python3.9/site-packages/torchreid/data/datasets/__init__.py:42, in init_image_dataset(name, **kwargs)
     37 if name not in avai_datasets:
     38     raise ValueError(
     39         'Invalid dataset name. Received "{}", '
     40         'but expected to be one of {}'.format(name, avai_datasets)
     41     )
---> 42 return __image_datasets[name](**kwargs)

Input In [4], in VeRiDataset.__init__(self, root, **kwargs)
     46         for image in IMAGES:
     47             cam_id = int(image.split('.jpg')[0].split('_')[-2])
---> 48             car_id = label_dict[int(image.split('.jpg')[0].split('_')[-1])]
     49             query_array.append((FOLDER_PATH +  dataset_type + "/" + image, car_id, cam_id))
     52 train = training_array

KeyError: 3

##############################################################################

Thank you !

**Comment by ashutoshIITK** [comment]
@klutzzykitty Thanks for detailed info. I was able to reproduce your error. You need to build the `torchreid` module from source because pip package does not support the latest version. The latest version is `1.4.0`.

Hope it solves your issue. I will update the repository with installation script soon.

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
I have updated the installation instructions. Please check and let me know if the problem still persists.

**Comment by klutzzykitty** [comment]
@ashutoshIITK Thanks for the quick response! 

Ah, so a newer version of `torchreid`  exists. That's something new I learnt. 
Will try out the new changes you've mentioned and get back.

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Yeah and you need to build it from the source. 
Let me know if this is resolved.

**Comment by klutzzykitty** [comment]
@ashutoshIITK 

Damn, have the same error after executing the updated instructions : (

Also tried with `python 3.7 and 3.9` 
`pytorch-cuda=11.7 and 11.3` versions, but it's the same behaviour. 


Some other methods I tried : 
####################################################################################
1) Have built `torchreid` from source 
```
Installed /home/vehicle_reid_working/VehicleReIdentificationDataset/deep-person-reid
Processing dependencies for torchreid==1.4.0
.
.
.
Using /root/anaconda3/envs/carla_reid/lib/python3.7/site-packages
Finished processing dependencies for torchreid==1.4.0

>>> print(f"current torch-reid version: {torchreid.__version__}")
current torch-reid version: 1.4.0
>>> 
>>> torch.cuda.is_available()
True

```
the updated shell script has `python setup.py install` method which builds the torchreid module. 
Tried with `python setup.py develop`  as well, but both resulted in the same error. 


2) Combinations of python  and pytorch-cuda versions 
`python 3.7` with `pytorch-1.13.1-cuda11.7` stable build and ` pytorch-1.12.1-cuda11.3 `
`python 3.9` with  `pytorch-1.13.1-cuda11.7` stable build and ` pytorch-1.12.1-cuda11.3 `

####################################################################################

System and package specs (if it comes in handy): 
################################################
OS: ubuntu 20.04 
GPU: Nvidia RTX 3090
CPU: Ryzen9 5950x
Conda: 23.1.0
CUDA: tried with both 11.7 and 11.3
################################################

pic for reference (    although it's not useful : )    )

![torch_reid_error_2](https://user-images.githubusercontent.com/118447577/217572408-cbba0a9d-7ed7-4127-922c-fdc411082f5e.png)

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Thanks! I am unable to reproduce this error now, but I am trying.

I can look it over a zoom call, if you want. My timezone is EST (Boston/NY).

**Comment by klutzzykitty** [comment]
@ashutoshIITK 
Thanks for that ! 
i'll first try to dig a little deeper and find a solution. 
If it doesn't bear fruit, i'll be sure to contact you. 

Would a Nvidia cuda docker have any issues with `torchreid`'s working?  

Regarding the trial to reproduce the error: 
If possible, you can try with Nvidia cuda 11.3.1 docker : `$docker pull nvcr.io/nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`
and then continuing with the same instructions in this repo. 

The only change in the `install_packages_reid.sh`  script would be to install pytorch with environment respective cuda version i.e. 
`$conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`

`install_packages_reid.sh`  can  also be run as-is , which installs pytorch with cuda 11.7 instead. 
(which I think shouldn't cause any issues as its backward compatible).

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Thanks! I tried the docker image and I do not get error in loading the dataset. I used python venv instead of conda, but that should not be the reason. Did you  correctly load the host folder directory (containing images) to the docker container? 

`sudo docker run -it -v /home/mdxuser/Desktop/Ph.D/GitHub/VehicleReIdentificationDataset/:/VehicleReIdentificationDataset/ -p 8888:8888 f97a05a20604 /bin/bash`

In above example, I just loaded the root directory of the repository, which also contains the dataset folder. In the Jupyter notebook, I only changed the `PATH_TO_DATASET = "/VehicleReIdentificationDataset/dataset/"`. 

With that, I was able to load the dataset successfully. Is that something you already tried and still getting the `KeyError`?

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Also, could you try without Docker to see if that works or not? Of course, I can also share my Docker image.

**Comment by klutzzykitty** [comment]
@ashutoshIITK 

Tried without docker, was limited to `pytorch 1.9.0 with cuda 11.1 `
it's the same behaviour without docker as well. 

Yeah, I suppose i'm pointing to the right path as well , have the `image`, `query` and `gallery` data directories inside `CARLA_dataset `folder. `PATH_TO_DATASET = "/home/reid/CARLA_dataset/"`

Noticed that the exit is triggered with `cam_id = 81` every time with or without docker  for which the `car_id` isn't fetched

```
=> Loading train (source) dataset
cam ID : 29
car ID : 5
cam ID : 21
car ID : 2
.
.
cam ID : 61
car ID : 29
cam ID : 32
car ID : 9
cam ID : 26
car ID : 38
cam ID : 81

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
```
This is within the `elif dataset_type == "image_query":`  condition of `VeRiDataset`  class. 

The car and cam IDs for `train` and `gallery` folders load properly tho.

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Thanks! Could you try to do some `try` and `except`, for loading `cam_id` and `car_id`. In the `Exception`, you may try to print `image` (path or filename), so that we can know which file is causing the problem. Try removing that file and see if that helps catching the real problem.

**Comment by klutzzykitty** [comment]
@ashutoshIITK 
Was away for a while. 
Here are some of the findings. 

1) Saw that only one of the IDs is` 0 based` instead of both cam and car ID being 0 based (the latter is what I guess `torchreid` requires ).  

2) Removing the images causing the problem (in query) resulted in the repetition of the same problem till the last set of images remained. Thus the problem may not be associated with the path or naming but with handling of the data-structure. 

3) Re-wired a completely new logic for obtaining the `train, gallery and query` arrays in `VeRiDataset` class and re-arranged the gallery and query data in a different manner. 

After this, re-id seems to be working on the shared carla vehicle dataset. 
Verified it with  `test_only=True`.

**Comment by ashutoshIITK** [comment]
@klutzzykitty 
Awesome! Thanks a lot for sharing the issue in detail. Glad that you are all set. Let me know if you have some other questions.
